### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by michal-bootcamp** [JoannaKu/Java-Script-11#1]
js:
- [x] dodaj srednik w 2 linii
- [x] `document.body.appendChild(list);` jest niepotrzebne
- [x] dla spojnosci uzywaj albo pojedynczego cudzyslowu, albo podwojnego, ale wtedy wszystkie tak samo
- [x] dodaj spacje w wyswietlanych itemach, zeby bylo `item 1` zamiast `item1`

**Comment by JoannaKu** [comment]
zrobione :)
